version: '3.8'

networks:
  ms-database:
    name: ms-database
    driver: bridge

services:
  ms-database:
    container_name: ms-database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: mindroot
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: minderaschool
    ports:
      - 5432:5432
    networks:
        - ms-database